import Foundation

extension BeautyDiaryState {
    static let seed = BeautyDiaryState(
        profile: UserProfileRecord(
            nickname: "精緻女孩",
            streakDays: 1,
            signature: "設定、成就、資源、數據管理",
            bodyFocus: "全身 / 局部訓練追蹤",
            skincareFocus: "混合肌保養與膚況記錄",
            themeName: "暖米白",
            notificationTime: "21:00"
        ),
        checklistItems: [
            ChecklistItem(id: UUID(), title: "護膚打卡", category: "變美"),
            ChecklistItem(id: UUID(), title: "頭髮保養", category: "變美"),
            ChecklistItem(id: UUID(), title: "美白計畫", category: "變美"),
            ChecklistItem(id: UUID(), title: "面部拉提/瑜珈", category: "變美"),
            ChecklistItem(id: UUID(), title: "運動打卡", category: "體態"),
            ChecklistItem(id: UUID(), title: "養生茶飲", category: "體態"),
            ChecklistItem(id: UUID(), title: "飲食記錄", category: "體態"),
            ChecklistItem(id: UUID(), title: "健康狀況", category: "體態"),
            ChecklistItem(id: UUID(), title: "閱讀打卡", category: "成長"),
            ChecklistItem(id: UUID(), title: "情緒記錄", category: "成長")
        ],
        routine: SkincareRoutine(
            steps: [
                RoutineStep(id: UUID(), period: .morning, name: "清潔", productName: nil, isChecked: false),
                RoutineStep(id: UUID(), period: .morning, name: "化妝水", productName: nil, isChecked: false),
                RoutineStep(id: UUID(), period: .morning, name: "精華液", productName: nil, isChecked: false),
                RoutineStep(id: UUID(), period: .morning, name: "眼霜", productName: nil, isChecked: false),
                RoutineStep(id: UUID(), period: .morning, name: "乳液/面霜", productName: nil, isChecked: false),
                RoutineStep(id: UUID(), period: .morning, name: "防曬", productName: nil, isChecked: false),
                RoutineStep(id: UUID(), period: .evening, name: "卸妝", productName: nil, isChecked: false),
                RoutineStep(id: UUID(), period: .evening, name: "清潔", productName: nil, isChecked: false),
                RoutineStep(id: UUID(), period: .evening, name: "化妝水", productName: nil, isChecked: false),
                RoutineStep(id: UUID(), period: .evening, name: "精華液", productName: nil, isChecked: false),
                RoutineStep(id: UUID(), period: .evening, name: "眼霜", productName: nil, isChecked: false),
                RoutineStep(id: UUID(), period: .evening, name: "乳液/面霜", productName: nil, isChecked: false)
            ]
        ),
        products: [],
        skinRecords: [],
        bodyMetricRecords: [],
        mealRecords: [],
        appointments: [],
        resourceItems: [],
        bookRecords: [],
        tutorialLinks: [
            TutorialLink(id: UUID(), title: "敏感肌晚間修護流程", url: "https://example.com/skincare-night"),
            TutorialLink(id: UUID(), title: "新手保養品疊擦順序", url: "https://example.com/product-order")
        ],
        punchRecords: [],
        achievements: [
            AchievementBadge(id: UUID(), title: "連續打卡王", detail: "連續打卡 7 天", unlocked: false),
            AchievementBadge(id: UUID(), title: "資源收藏家", detail: "新增 10 筆資源", unlocked: false),
            AchievementBadge(id: UUID(), title: "護膚紀錄員", detail: "完成 5 次膚況紀錄", unlocked: false)
        ],
        exportHistory: [],
        resourceFilter: .all,
        resourceImportHistory: [],
        pendingImportDraft: nil,
        resourceSyncQueue: [],
        hairCareRecords: [],
        bodySkinRecords: [],
        faceLiftActions: [],
        faceLiftPunches: [],
        faceLiftRatings: [],
        bodyProducts: [],
        hairProducts: [],
        hairAppointments: [],
        washFrequencyDays: 2,
        careFrequencyDays: 7,
        whiteningProductUsages: [],
        shadeTrackingRecords: [],
        beforeAfterPhotos: [],
        favoriteRecipes: [],
        faceShape: nil,
        savedHairstyles: [],
        makeupInspirations: [],
        exercisePunches: [],
        customExercises: [],
        targetWeight: nil,
        targetBodyFat: nil,
        trainingSchedule: [],
        symptomRecords: [],
        bodyAlbumPhotos: [],
        courses: [],
        knowledgeNotes: [],
        videoLearningRecords: [],
        selfAffirmations: [],
        visionBoardItems: [],
        gratitudeEntries: [],
        moodEntries: [],
        transactions: [],
        budgetCategories: [],
        beautyFundTransactions: [],
        wishes: [],
        shoppingItems: [],
        checklistCompletions: [],
        menstrualRecords: [],
        nourishmentRecipes: [],
        bodyConstitution: nil
    )
}
